### ISSUE TITLE
Allow queue population directly from a state file

### ISSUE THREAD

**Issue by t-young31** [UCLH-Foundry/PIXL#141]
Currently if `pixl stop` has been run with messages on a queue then when restarting to put the messages back onto the queue needs `pixl populate <filename>.csv --queues <queue name>`, which is counter intuitive.

**Comment by stefpiatek** [comment]
Preferred way to deal with this is #198

**Comment by t-young31** [comment]
as long as no one runs a `docker volume prune` from under you!
