### ISSUE TITLE
[Project PIXL] README and pyproject consistency across modules (add README for pixl_dcmd)

### ISSUE THREAD

**Issue by ruaridhg** [UCLH-Foundry/PIXL#167]
### Definition of Done / Acceptance Criteria

- [x] Add some instructions for running tests for pixl_dcmd as there currently are none
- [ ] Check consistency of README and pyproject.toml across modules

### Details and Comments

If it turns out that the indvidual `pyproject.toml` files are all identical, we could replace them with one main root `pyprojec.toml` file.

**Comment by jstutters** [comment]
Install and test procedure added to pixl_dcmd README in commit fc2ea7c which also moves dcmd to `pyproject.toml.`

**Comment by stefpiatek** [comment]
done!
