### ISSUE TITLE
Export current extract parquet files to DSH

### ISSUE THREAD

**Issue by stefpiatek** [UCLH-Foundry/PIXL#192]
### Definition of Done / Acceptance Criteria

The public parquet files are zipped and copied via FTPS to the DSH in a directory for the extract name slug

### Testing

Use the same testing setup for #190, but instead testing the parquet files 

### Dependencies

After #190 

### Details and Comments

Could probably do a manual upload to the DSH instead if required.
_Might_ be a nice option to merge the two export commands.

**Comment by milanmlft** [comment]
Where should the parquet files end up? Just in the `<project-slug>/` directory, next to [the DICOM zip files](#226)?

**Comment by stefpiatek** [comment]
> Where should the parquet files end up? Just in the <project-slug>/ directory, next to https://github.com/uclh-foundry/pixl/issues/190?

yep. Maybe worth copying everything in the `current_extracts` dir to `<project_slug>/parquet` so that its a bit cleaner
