### ISSUE TITLE
Keep rabbitmq state instead of draining to state file

### ISSUE THREAD

**Issue by stefpiatek** [UCLH-Foundry/PIXL#198]
### Definition of Done / Acceptance Criteria

Rabbitmq messages are presevered between runs within a docker project, so we won't have to drain the messages of a queue into a state file

### Testing

Will only really need to do some testing taking down the rabbitmq while it has messages and make sure that when it spins up it has the same messages

### Documentation

Remove any reference to state file and document that the rabbitmq queues are preserved between runs 

### Details and Comments

It looks like rabbitmq logs and queues are persisted by [Node Name](https://www.rabbitmq.com/cli.html#node-names) and we can se that through an environment variable, perhaps also setting hostname in [docker compose](https://stackoverflow.com/questions/41330514/docker-rabbitmq-persistency). Then we'll just need to have a docker compose volume that maps `/var/lib/rabbitmq/mnesia/`

Would fix #282

**Comment by peshence** [comment]
I don't think the state file's purpose is failure recovery as we only call it in the "stop" CLI command, not the "kill" one. Instead, it gives the option to stop/pause message consumption while saving whatever messages have not been processed. 

Is that really something we want to remove?

**Comment by stefpiatek** [comment]
yeah, recovery was wrong but essentially being able to pause between runs was the intention. Yep we do, rabbitmq is stateful (and I'd trust it more than writing the queue to a file), we're not going to be working on a GAE where someone can do a prune of volumes out from under us so this just adds complexity
