### ISSUE TITLE
PIXL pipeline: improved test coverage of radiology report anonymisation

### ISSUE THREAD

**Issue by skeating** [UCLH-Foundry/PIXL#204]
### Definition of Done / Acceptance Criteria

- mocked up radiology reports used in high level testing within the pixl_ehr service. ensure PID is absent and expected data is present

### Dependencies

Will depend on where radiology report de-identification is due to happen. May not be in PIXL

**Comment by stefpiatek** [comment]
De-identification from cogstack so no need to test
