### ISSUE TITLE
Clean up Azure-related code in PIXL

### ISSUE THREAD

**Issue by milanmlft** [UCLH-Foundry/PIXL#215]
### Definition of Done / Acceptance Criteria

All Azure-related code has been removed or at least commented to describe why it's still there.

### Details and Comments

There is some leftover code for interacting with Azure that doesn't seem to be used anymore:
- https://github.com/UCLH-Foundry/PIXL/blob/22aa62ca7aa4e6b0f492a238f6e606607b3edc76/orthanc/orthanc-anon/plugin/pixl.py#L65
- https://github.com/UCLH-Foundry/PIXL/blob/22aa62ca7aa4e6b0f492a238f6e606607b3edc76/pixl_ehr/src/pixl_ehr/main.py#L65
- ...

Could be cleaned up as part of other development tasks or as one big "clean up" PR

**Comment by stefpiatek** [comment]
We still want this in as an option to publish to azure so closing!
