### ISSUE TITLE
Do we need so many hashing API endpoints?

### ISSUE THREAD

**Issue by jeremyestein** [UCLH-Foundry/PIXL#218]
We currently have:
* `/hash`
* `/hash-accession-number`
* `/hash-mrn`

The implementations of these differ slightly or not at all. Is there a genuine requirement that we were trying to capture here?

`/hash-accession-number` truncates the hash to 16 characters - what is the reason for this?

For reference:
https://github.com/UCLH-Foundry/PIXL/blob/b51943f78af87cbdc0647408354e0dbc7199d759/hasher/src/hasher/endpoints.py#L30-L59

**Comment by stefpiatek** [comment]
> /hash-accession-number truncates the hash to 64 bits - what is the reason for this?

Ooh this one has a reason, the DICOM field is limited in length so its truncating for that

> /hash-mrn

I think this is a legacy issue and should be removed
