### ISSUE TITLE
Replace pixl_dcmd setup.py with pyproject.toml

### ISSUE THREAD

**Issue by jstutters** [UCLH-Foundry/PIXL#255]
### Definition of Done / Acceptance Criteria

pyproject.toml exists in the module root and defines the module and its dependencies.

### Testing

Existing tests for pixl_dcmd pass when module is freshly installed.

### Details and Comments

Other PIXL modules are already using pyproject.toml and the current setup.py contains a circular dependency.

**Comment by ruaridhg** [comment]
Possibly done due to orthanc working with a specific version of Python, but don't see why it can't be a pyproject.toml

**Comment by stefpiatek** [comment]
certainly can, required 3.9 because of orthanc docker image having that version of python
