### ISSUE TITLE
Better description of pixl_dcmd in README 

### ISSUE THREAD

**Issue by jstutters** [UCLH-Foundry/PIXL#257]
### Definition of Done / Acceptance Criteria

pixl_dcmd explains where the module fits within the project. 

### Details and Comments

pixl_dcmd is a dependency of the DICOM anonymisation plugin defined within orthanc_anon.  Mention that it works on DICOM headers.

**Comment by ruaridhg** [comment]
Orthanc container works with python 3.9 so is in a separate module from pixl_core and has limited scope i.e. interacting with orthanc-anon

**Comment by milanmlft** [comment]
Fixed in #256
