### ISSUE TITLE
Allow PIXL DB tables to be updated in production

### ISSUE THREAD

**Issue by stefpiatek** [UCLH-Foundry/PIXL#270]
### Definition of Done / Acceptance Criteria

- [ ] instead of creating tables from sqlalchemy in postgres/create_pixl_tbls.py, use define the tables in alembic migrations and run them before we run the imaging-api/pacs-api server as part of the run command

### Testing

shouldn't need any changing

### Documentation

Add documentation on alembic being used for the postgres service

### Details and Comments

- We expect that the pixl DB will change over time, and want to handle this in an automated way that we can test with development versions
- Because we're defining our tables in sqlachemy, [alembic](https://alembic.sqlalchemy.org/en/latest/) is a straightforward choice. Its a bit of duplication of information, but does mean that we can update our production database in a controlled way with rollbacks if required
- the imaging pipeline is the only part that depends on the `pipeline` tables, so running this on startup of the container makes sense

**Comment by jstutters** [comment]
Underway in [jstutters/270-use-alembic-for-database-table-creation](https://github.com/UCLH-Foundry/PIXL/tree/jstutters/270-use-alembic-for-database-table-creation).
