### ISSUE TITLE
Use well tested anonymisation library instead of our own for DICOM tags

### ISSUE THREAD

**Issue by stefpiatek** [UCLH-Foundry/PIXL#291]
### Definition of Done / Acceptance Criteria

- [x] Create an options analysis for libraries which can be used to carry out tag operations which can 
  - [x] read in a config file/dictionary for tag operations
  - [x] parse datetimes and shift them
  - [x] remove tag
  - [x] replace tag with empty value
  - [x] apply a custom function to the tag 
- [ ] Document options analysis in PIXL repo
- From [options analysis](https://uclh.slab.com/posts/dicom-tag-processing-1cdo30rq#h9d4r-recommendations) we've decided on https://github.com/KitwareMedical/dicom-anonymizer
  - [ ] Use the library instead of our custom code, may require restructuring of the existing tag operations yaml file

### Documentation

- [ ] Update orthanc anon documentation 

### Details and Comments

Currently we're rolling our own DICOM tag operations which is error prone and I'd expect exists elsewhere

**Comment by jstutters** [comment]
One for consideration: https://github.com/KitwareMedical/dicom-anonymizer

@HChughtai mentioned something from the flywheel.io team.

**Comment by HChughtai** [comment]
I was just looking at it and checking if it was still active (which I think it is) - https://flywheel-io.gitlab.io/public/migration-toolkit/

My plan is to find a few popular options and look into them in more detail. So more options are good!

The other ones I've come across
- https://pydicom.github.io/deid/
- https://mircwiki.rsna.org/index.php?title=MIRC_CTP (not a Python option)

**Comment by stefpiatek** [comment]
Need to work on decision on whether we continue with plugin based or more scalable open source options

**Comment by HChughtai** [comment]
Writing up my options analysis on Slab at [DICOM Tag Processing](https://uclh.slab.com/posts/dicom-tag-processing-1cdo30rq)

**Comment by HChughtai** [comment]
Options analysis now has some [broad recommendations](https://uclh.slab.com/posts/dicom-tag-processing-1cdo30rq#h9d4r-recommendations) that I'll chat with @stefpiatek about this week

> The three Python libraries considered have broadly the same feature sets. However the Flywheel-Migration library seems to be less supported compared to the Kitware Medical dicom-anonymizer and Pydicom deid. If we choose to go with either of the latter two then the existing Orthanc-based approach can be retained.
> 
> Alternatively we may wish to take this opportunity to rearchitect the orthanc-anon component to fit current and expected new requirements.

Next steps are:

- [ ] Decide on whether to stick with current DICOM tag processing/anonymisation architecture, or to remove orthan-anon in favour of a different approach

- [ ] Depending on previous decision, decide on specific option in the analysis above to implement/look into further

**Comment by stefpiatek** [comment]
closed by #366
