### ISSUE TITLE
Allow orthanc anon to run without connecting to Azure

### ISSUE THREAD

**Issue by stefpiatek** [UCLH-Foundry/PIXL#295]
### Definition of Done / Acceptance Criteria

- [ ] Orthanc anon can be configured not to try to connect to azure (as this currently blocks upload work)
  - [ ] `.env` file should be able to configure where whether we ever try to connect to azure
  - [ ] `pixl.py` plugin in orthanc anon uses the variable to gate connection to azure 
    - `AzureDICOMTokenRefresh` and `AzureAccessToken` should not be run if the config disables it 

### Details and Comments

Had done some commenting out of code to get test out upload into DSH in `pixl_test`, should have a long term solution for this

**Comment by milanmlft** [comment]
So this is why I added https://github.com/UCLH-Foundry/PIXL/blob/044286040f88d3219c35a2a46ea14a2e4705e17e/orthanc/orthanc-anon/plugin/pixl.py#L217-L219 in #268. `_azure_available()` checks if the `AZ_DICOM_ENDPOINT_CLIENT_ID` env variable is set, and if it's not then `AzureDICOMTokenRefresh` doesn't get called. But might have missed something. Which lines of code did you have to comment out to get it to work?
