### ISSUE TITLE
Convert ehr api to export api

### ISSUE THREAD

**Issue by stefpiatek** [UCLH-Foundry/PIXL#321]
### Definition of Done / Acceptance Criteria

Once we have finished off the 100 days integration of new model for redaction in UCLH-Foundry/the-rolling-skeleton/issues/214 , strip out the emap star querying from PIXL

- [x] Remove tables from PIXL DB relating to EHR data (this is now in the OMOP extract)
- [x] Convert ehr api to export api and rename endpoints for exporting data (see top level document for step naming)
- [x] Remove redundant tests, fake cogstack api, fake emap star etc.
- [x] the pixl CLI create radiology linker table on the fly (and writes to export dir): on export will read in the omop data, query the pixl pipeline database for all images in the project name, and merge the omop data with the hashed imaging identifier to write the linker parquet file
- [ ] Rename EHR env vars and document that these need renaming in config file
- [x] Remove ehr queue
- [x] move orthanc anon's ftps export into the export api. orthanc anon tells export api that this resource is ready for export

### Documentation

- [ ] Update documentation to reflect exporting function, documenting pathways for exporting images and parquet files, imaging alone and parquet alone?

### Dependencies

- [ ] UCLH-Foundry/the-rolling-skeleton/issues/214

**Comment by jeremyestein** [comment]
@stefpiatek Am assuming the `pixl az-copy-ehr` command can be removed?

**Comment by stefpiatek** [comment]
> @stefpiatek Am assuming the pixl az-copy-ehr command can be removed?

Yep!
