### ISSUE TITLE
Enable consuming pixl queue messages by default

### ISSUE THREAD

**Issue by stefpiatek** [UCLH-Foundry/PIXL#323]
### Definition of Done / Acceptance Criteria

- [ ] As a PIXL pipeline runner, I don't want to have to start consuming from queues manually, instead the default behaviour on startup should be to consume from the queues at the default rate

### Dependencies

- [ ] #311

**Comment by peshence** [comment]
duplicate of #322 ?

**Comment by stefpiatek** [comment]
Ah yes it is, that didn't have a milestone added so didn't spot it when creating 🤦🏻
