### ISSUE TITLE
Setting up PIXL in my local host device and adding few recommendations with a fresh perspective

### ISSUE THREAD

**Issue by mxochicale** [UCLH-Foundry/PIXL#422]
I am new to PIXL so the first idea that comes to mind is to have an on-boarding template listing steps on how to setup PIXL locally and then remotely.  
* [x] clone repo, create python env, pip install PIXL and pass tests
* [x] add templates for issues (bugs, new features, something is not working), PRs, onboarding, etc
* [x] Priorities for issues (might be an overkill, as it is already in Project dashboard labels )
* [x] AOB

**Comment by stefpiatek** [comment]
> Hi @stefpiatek @p-j-smith
> 
> I managed to install dev deps using `pip install -e ../pixl_core -e ../pytest-pixl -e .[test] -e .[dev]` but I get some failures with `test_docker_commands.py`

Just updating here but it seems like its the `--dry-run` flag not being available for Miguel's docker, he's looking at updating this and documenting the updates

**Comment by stefpiatek** [comment]
Docker version looks the same and dry-run is in the [docs](https://docs.docker.com/reference/cli/docker/compose/#use-dry-run-mode-to-test-your-command) so should be available in linux.

Edit: Oh I think its the docker compose version that you'll need to update

```
Docker Compose version v2.28.1-desktop.1
```

**Comment by mxochicale** [comment]
some notes to be added in relevant issues 
* Do we want to remove versions of deps in https://github.com/UCLH-Foundry/PIXL/blob/main/cli/pyproject.toml (core does not have a version)?
* Duplicated requirements for test and dev in https://github.com/UCLH-Foundry/PIXL/blob/main/cli/pyproject.toml and https://github.com/UCLH-Foundry/PIXL/blob/main/pixl_core/pyproject.toml and other pixl_* packages
* Duplication of setups instructions:
https://github.com/UCLH-Foundry/PIXL/tree/main?tab=readme-ov-file#development
https://github.com/UCLH-Foundry/PIXL/tree/main/cli#installation
https://github.com/UCLH-Foundry/PIXL/blob/main/docs/setup/developer.md

**Comment by stefpiatek** [comment]
Thanks!. I'm pretty fine with duplication of documentation, so you can stumble across information as an when you need it. Will make issues for the other ones
