### ISSUE TITLE
We need a version release summary and a plan for release cycle

### ISSUE THREAD

**Issue by mxochicale** [UCLH-Foundry/PIXL#427]
* Would the next release of `PIXL` be 0.1.0 with updates for their next module versions? Currently, `core` package release version is [`0.0.1`](https://github.com/UCLH-Foundry/PIXL/blob/main/pixl_core/pyproject.toml#L3) and pixl modules have the following versions:
  * name = "pixl_cli" version = "0.0.4"
  * name = "hasher" version = "0.0.1"
  * name = "pixl_dcmd" version = "0.0.2"
  * name = "pixl_export" version = "0.0.2"
  * name = "pixl_imaging" version = "0.0.2"
  * name = "pytest-pixl" version = "0.0.1"

* We might need a minimal release cycle for `PIXL`: For instance one release candidate might be `0.1.0-rc` and various subversion denoted by * in `0.1.*` for full bug-fix support (inspired by https://peps.python.org/_images/pep-0602-example-release-calendar.png at https://peps.python.org/pep-0602/)?

**Comment by stefpiatek** [comment]
closing for now as we are producing an application for our usage, and don't have a fixed rate of development but instead is project-based
