### ISSUE TITLE
Use XNAT as an endpoint

### ISSUE THREAD

**Issue by stefpiatek** [UCLH-Foundry/PIXL#471]
### Definition of Done / Acceptance Criteria

As an IoN DRI project, I want my study to be exported to XNAT via the XNAT API.

### Testing

- [X] unit test for exporting to an XNAT instance that is spun up in docker

### Documentation

- [x] update allowed endpoints in config
- [x] update documentation on endpoints that have been built

### Dependencies

Need to find out

- [ ] How we want to deal with project names / IDs in XNAT
- [ ] How we deal with routing to XNAT endpoint

### Details and Comments

*No response*

**Comment by p-j-smith** [comment]
After offline discussions with @stefpiatek, @HChughtai and @p-j-smith, we will:
- use a 1:1 mapping between project names on PIXL and XNAT
- set the slugified project name in PIXL to the XNAT project ID (a shorthand for the project that is immutable and up to 14 characters long)
- need to modify PIXL / `dri-to-pixl` to handle the case where a study name changes in Clarity. The name will not change in XNAT, so we will need to handle merging two projects that map to the same endpoint.
- use the return status from XNAT to confirm upload was successful or retry sending if unsuccessful

Pre-requisites for pushing to an XNAT instance:
- projects will first need to be created on XNAT (we will not have permissions to create them with PIXL)
- a single `pixl` user will be added to all relevant XNAT projects with read and write access. We could use time-limited tokens to authenticate
