### ISSUE TITLE
Bump module versions to `v0.1.0` and create release

### ISSUE THREAD

**Issue by milanmlft** [UCLH-Foundry/PIXL#473]
This will be the version of PIXL that will be used for the PINPOINT project

- [x] Bump version for each module to `0.1.0
- [x] Add `0.1.0` tag
- [x] Create GitHub release and write some release notes
- [ ] Bump modules to `0.2.0-rc` after release

**Comment by mxochicale** [comment]
Good call @milanmlft @stefpiatek  on having v0.1.0 for pixl
See https://github.com/UCLH-Foundry/PIXL/issues/427  as you might like to version control others package deps (pixl_cli, hasher, pixl_dcmd, etc) and think of a minimal release cycle (0.1.0-rc (1-month?) and 0.1.0, (6-months?), 0.2.0-rc (1-month?) and 0.2.0, (6-months?, etc), your choice on the time frames of the release cycle. Happy to help with the review when is ready

**Comment by stefpiatek** [comment]
I think it might be a bit premature optimisation to aim for a release schedule. AFAIK this is being used as a standalone deployment only at UCLH so we can decide on release when we feel like we've made substantial changes. Up for having the next version as a release candidate after we've merged this into main and created a release & tagged on github though

**Comment by stefpiatek** [comment]
I think it'd be `0.2.0-rc` because its a release candidate for the next release
